layerrules = true
kill_bind = "ctrl+shift+alt, h"
version = 1

[windows]
scale = 8.5
items_per_row = 5

[windows.overview]
strip_html_from_workspace_title = true
key = "super_l"
modifier = "super"
filter_by = []
hide_filtered = false

[windows.overview.launcher]
default_terminal = "alacritty"
launch_modifier = "ctrl"
width = 650
max_items = 5
show_when_empty = true
animate_launch_ms = 250

[windows.overview.launcher.plugins.applications]
run_cache_weeks = 4
show_execs = true
show_actions_submenu = false

[windows.overview.launcher.plugins.calc]

[windows.overview.launcher.plugins.path]

[windows.switch]
modifier = "alt"
filter_by = []
show_workspaces = false
