import = [
    "~/.config/alacritty/themes/coralina.toml"
]

[bell]
animation = "EaseOutExpo"
duration = 0

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
startup_mode = "Maximized"

[font]
size=18.5

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[cursor]
style.blinking = "Always"
style.shape = "Block"

[colors.cursor]
text = "CellBackground"
cursor = "#ffeb95"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

# [[hints.enabled]]
# regex = "DEV-[0-9]+"
# command = { program = "/Users/vitor.oliveira/custom/open_ticket.sh", args = [  ] }
# mouse = { enabled = true }

# #########################
# ## Keyboard navigation ##
# #########################

# HOME
[[keyboard.bindings]]
key = "Left"
mods = "Super"
chars = "\u001bOH"
[[keyboard.bindings]]
key = "Down"
mods = "Super"
chars = "\u001bOH"
[[keyboard.bindings]]
key = "Down"
mods = "Alt"
chars = "\u001bOH"

# END
[[keyboard.bindings]]
key = "Right"
mods = "Super"
chars = "\u001bOF"
[[keyboard.bindings]]
key = "Up"
mods = "Super"
chars = "\u001bOF"
[[keyboard.bindings]]
key = "Up"
mods = "Alt"
chars = "\u001bOF"

# Move cursor word by word
[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001BF"
[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001BB"

# ############################
# ## tmux plugins shortcuts ##
# ############################

# C-K (Pick a sesh)
[[keyboard.bindings]]
key = "L"
mods = "Super"
chars = "\u0001\u004b"

# Next session: CMD + Option + L
[[keyboard.bindings]]
key = "L"
mods = "Super|Alt"
chars = "\u0001\u0029"

# C-T (Sesh popup)
[[keyboard.bindings]]
key = "L"
mods = "Super|Shift"
chars = "\u0001\u0054"

# tmux-fzf-url
[[keyboard.bindings]]
key = "u"
mods = "Super"
chars = "\u0001\u0075"

# tmux-thumbs
[[keyboard.bindings]]
key = "c"
mods = "Super|Shift"
chars = "\u0001\u0020"

# ############################
# ## better tmux navigation ##
# ############################

[[keyboard.bindings]]
key = "T"
mods = "Super"
command = { program = "/opt/homebrew/bin/tmux", args = ["new-window"] }

[[keyboard.bindings]]
key = "W"
mods = "Super"
chars = "\u0001\u0078"

[[keyboard.bindings]]
key = "{"
mods = "Super|Shift"
command = { program = "/opt/homebrew/bin/tmux", args = ["previous-window"] }

[[keyboard.bindings]]
key = "}"
mods = "Super|Shift"
command = { program = "/opt/homebrew/bin/tmux", args = ["next-window"] }

[[keyboard.bindings]]
key = "1"
mods = "Super"
chars = "\u0001\u0031"

[[keyboard.bindings]]
key = "2"
mods = "Super"
chars = "\u0001\u0032"

[[keyboard.bindings]]
key = "3"
mods = "Super"
chars = "\u0001\u0033"

[[keyboard.bindings]]
key = "4"
mods = "Super"
chars = "\u0001\u0034"

[[keyboard.bindings]]
key = "5"
mods = "Super"
chars = "\u0001\u0035"

[[keyboard.bindings]]
key = "6"
mods = "Super"
chars = "\u0001\u0036"

[[keyboard.bindings]]
key = "7"
mods = "Super"
chars = "\u0001\u0037"

[[keyboard.bindings]]
key = "8"
mods = "Super"
chars = "\u0001\u0038"

[[keyboard.bindings]]
key = "9"
mods = "Super"
chars = "\u0001\u0039"
