
[bell]
animation = "EaseOutExpo"
duration = 0

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
startup_mode = "Maximized"

[font]
size=18.5

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[cursor]
style.blinking = "Always"
style.shape = "Block"

[colors.cursor]
text = "CellBackground"
cursor = "#ffeb95"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

# [[hints.enabled]]
# regex = "DEV-[0-9]+"
# command = { program = "/Users/vitor.oliveira/custom/open_ticket.sh", args = [  ] }
# mouse = { enabled = true }

# #########################
# ## Keyboard navigation ##
# ## Hex dump: xxd -ps   ##
# #########################

# HOME
[[keyboard.bindings]]
key = "Left"
mods = "Super"
chars = "\u001bOH"
[[keyboard.bindings]]
key = "Down"
mods = "Super"
chars = "\u001bOH"
[[keyboard.bindings]]
key = "Down"
mods = "Alt"
chars = "\u001bOH"

# END
[[keyboard.bindings]]
key = "Right"
mods = "Super"
chars = "\u001bOF"
[[keyboard.bindings]]
key = "Up"
mods = "Super"
chars = "\u001bOF"
[[keyboard.bindings]]
key = "Up"
mods = "Alt"
chars = "\u001bOF"

# Move cursor word by word
[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001BF"
[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001BB"

# Change Directory: ALT + D
[[keyboard.bindings]]
key = "D"
mods = "Alt"
chars = "cd **\u0009"

# ############################
# ## tmux plugins shortcuts ##
# ############################

# C-K (Pick a sesh)
[[keyboard.bindings]]
key = "S"
mods = "Super"
chars = "\u0001\u004b"

# Next session: Option + S
[[keyboard.bindings]]
key = "S"
mods = "Alt"
chars = "\u0001\u0029"

# C-T (Sesh popup)
[[keyboard.bindings]]
key = "L"
mods = "Super|Shift"
chars = "\u0001\u0054"

# tmux-fzf-url
[[keyboard.bindings]]
key = "u"
mods = "Super"
chars = "\u0001\u0075"

# tmux-thumbs
[[keyboard.bindings]]
key = "c"
mods = "Super|Shift"
chars = "\u0001\u0020"

# ##########################
# ## tmux split shortcuts ##
# ##########################

# Split window horizontally: Option -
[[keyboard.bindings]]
key = "-"
mods = "Alt"
chars = "\u0001\u002d"

# Split window vertically: Option /
[[keyboard.bindings]]
key = "/"
mods = "Alt"
chars = "\u0001\u002f"

# ######################
# ##  general shortcuts ##
# ######################

# Show Clock: Super + c
[[keyboard.bindings]]
key = "c"
mods = "Super"
chars = "\u0001\u0074"

# Rename current window: F2 -> C-a ,
[[keyboard.bindings]]
key = "F2"
chars = "\u0001\u002c"

# Show pane numbers: Option 0
[[keyboard.bindings]]
key = "0"
mods = "Alt"
chars = "\u0001\u0071"

# ############################
# ## better tmux navigation ##
# ############################

# Next pane: Option + ]
[[keyboard.bindings]]
key = "]"
mods = "Alt"
chars = "\u0001\u006f"

# Previous pane: Option + [
[[keyboard.bindings]]
key = "["
mods = "Alt"
chars = "\u0001\u006b"

# Zoom the active pane: Option + z
[[keyboard.bindings]]
key = "z"
mods = "Alt"
chars = "\u0001\u007a"

# Back to last pane: Option + P
[[keyboard.bindings]]
key = "p"
mods = "Alt"
chars = "\u0001\u003b"

[[keyboard.bindings]]
key = "T"
mods = "Super"
command = { program = "/opt/homebrew/bin/tmux", args = ["new-window"] }

[[keyboard.bindings]]
key = "x"
mods = "Super"
chars = "\u0001\u0078"

[[keyboard.bindings]]
key = "{"
mods = "Super|Shift"
command = { program = "/opt/homebrew/bin/tmux", args = ["previous-window"] }

[[keyboard.bindings]]
key = "}"
mods = "Super|Shift"
command = { program = "/opt/homebrew/bin/tmux", args = ["next-window"] }

# ####################################
# ## tmux direct navigate to window ##
# ####################################

[[keyboard.bindings]]
key = "1"
mods = "Super"
chars = "\u0001\u0031"

[[keyboard.bindings]]
key = "2"
mods = "Super"
chars = "\u0001\u0032"

[[keyboard.bindings]]
key = "3"
mods = "Super"
chars = "\u0001\u0033"

[[keyboard.bindings]]
key = "4"
mods = "Super"
chars = "\u0001\u0034"

[[keyboard.bindings]]
key = "5"
mods = "Super"
chars = "\u0001\u0035"

[[keyboard.bindings]]
key = "6"
mods = "Super"
chars = "\u0001\u0036"

[[keyboard.bindings]]
key = "7"
mods = "Super"
chars = "\u0001\u0037"

[[keyboard.bindings]]
key = "8"
mods = "Super"
chars = "\u0001\u0038"

[[keyboard.bindings]]
key = "9"
mods = "Super"
chars = "\u0001\u0039"

# ##################################
# ## tmux direct navigate to pane ##
# ##################################

[[keyboard.bindings]]
key = "1"
mods = "Alt"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-pane", "-t", "1"] }

[[keyboard.bindings]]
key = "2"
mods = "Alt"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-pane", "-t", "2"] }

[[keyboard.bindings]]
key = "3"
mods = "Alt"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-pane", "-t", "3"] }

[[keyboard.bindings]]
key = "4"
mods = "Alt"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-pane", "-t", "4"] }

[[keyboard.bindings]]
key = "5"
mods = "Alt"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-pane", "-t", "5"] }

[[keyboard.bindings]]
key = "6"
mods = "Alt"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-pane", "-t", "6"] }

[[keyboard.bindings]]
key = "7"
mods = "Alt"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-pane", "-t", "7"] }

[[keyboard.bindings]]
key = "8"
mods = "Alt"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-pane", "-t", "8"] }

[[keyboard.bindings]]
key = "9"
mods = "Alt"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-pane", "-t", "9"] }

[general]
import = [
    "~/.config/alacritty/themes/coralina.toml"
]
