cp ../resources/.githelpers         ~/.githelpers
cp ../resources/.gitignore          ~/.gitignore
cp ../resources/.gitconfig.osx      ~/.gitconfig
cp ../resources/.gitk               ~/.gitk
cp ../resources/.railsrc            ~/.railsrc
cp ../resources/.gemrc              ~/.gemrc
cp ../resources/.tigrc              ~/.tigrc
cp ../resources/.ackrc              ~/.ackrc
cp ../resources/.agignore           ~/.agignore
