ln -s ~/dotfiles/resources/.githelpers         ~/.githelpers
ln -s ~/dotfiles/resources/.gitignore          ~/.gitignore
ln -s ~/dotfiles/resources/.gitconfig.ubuntu   ~/.gitconfig
ln -s ~/dotfiles/resources/.gitk               ~/.gitk
ln -s ~/dotfiles/resources/.railsrc            ~/.railsrc
ln -s ~/dotfiles/resources/.gemrc              ~/.gemrc
ln -s ~/dotfiles/resources/.tigrc              ~/.tigrc
ln -s ~/dotfiles/resources/.ackrc              ~/.ackrc
ln -s ~/dotfiles/resources/.agignore           ~/.agignore
